language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install tox tox-travis coveralls
  - pip install setuptools -U
  - python setup.py install
script:
  - tox
after_success:
  - coverage run --source=iiif_validator setup.py test
  - coveralls
